import { describe, expect, it, vi } from "vitest";
import { TinyFishClient, TinyFishError } from "../src/tinyfish-client.js";
const response = (body: unknown, init: ResponseInit = {}) => new Response(JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" }, ...init });
describe("TinyFishClient", () => {
  it("sends the API key and encoded search parameters", async () => { const http = vi.fn().mockResolvedValue(response({ results: [] })); await new TinyFishClient({ apiKey: "secret", fetchImpl: http }).search({ query: "a & b", count: 3, language: "en" }); expect(http.mock.calls[0][0]).toBe("https://api.search.tinyfish.ai/?query=a+%26+b&count=3&language=en"); expect(http.mock.calls[0][1].headers["X-API-Key"]).toBe("secret"); });
  it("sends a batch fetch payload and markdown format", async () => { const http = vi.fn().mockResolvedValue(response({ results: [] })); await new TinyFishClient({ apiKey: "secret", fetchImpl: http }).fetch({ urls: ["https://example.com"], format: "markdown" }); expect(http.mock.calls[0][0]).toBe("https://api.fetch.tinyfish.ai/"); expect(JSON.parse(http.mock.calls[0][1].body)).toEqual({ urls: ["https://example.com"], format: "markdown" }); });
  it("throws a redacted error for non-2xx responses", async () => { const http = vi.fn().mockResolvedValue(new Response("secret", { status: 500 })); await expect(new TinyFishClient({ apiKey: "secret", fetchImpl: http }).search({ query: "x" })).rejects.toSatisfy((e: Error) => !e.message.includes("secret")); });
  it("classifies auth, rate limit and transient responses", async () => { for (const [status, kind] of [[401, "auth"], [429, "rate-limit"], [503, "transient"]] as const) { const http = vi.fn().mockResolvedValue(new Response("", { status, headers: { "retry-after": "10" } })); await expect(new TinyFishClient({ apiKey: "secret", fetchImpl: http }).search({ query: "x" })).rejects.toMatchObject({ kind }); } });
  it("aborts a request at the configured timeout", async () => { const http = vi.fn((_url, init) => new Promise((_resolve, reject) => init.signal.addEventListener("abort", () => reject(new Error("aborted"))))); await expect(new TinyFishClient({ apiKey: "secret", timeoutMs: 1, fetchImpl: http }).search({ query: "x" })).rejects.toMatchObject({ kind: "timeout" }); });
});
